"""empty message

Revision ID: 2b9d7c4dadd3
Revises: 
Create Date: 2020-08-01 03:29:20.502111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9d7c4dadd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('profession_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('student_level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opp_type', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('dpplication_deadline', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paying', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level'], ['student_level.level_id'], ),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organisations_email'), 'organisations', ['email'], unique=True)
    op.create_index(op.f('ix_organisations_website'), 'organisations', ['website'], unique=True)
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('mentor', sa.Boolean(), nullable=True),
    sa.Column('profession_type', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('linkedIn', sa.String(length=120), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['profession_type'], ['profession_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_email'), 'professionals', ['email'], unique=True)
    op.create_index(op.f('ix_professionals_linkedIn'), 'professionals', ['linkedIn'], unique=True)
    op.create_index(op.f('ix_professionals_name'), 'professionals', ['name'], unique=False)
    op.create_index(op.f('ix_professionals_username'), 'professionals', ['username'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=False),
    sa.Column('mentorship', sa.Boolean(), nullable=True),
    sa.Column('mentor', sa.Integer(), nullable=True),
    sa.Column('mentor_type', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['level'], ['student_level.level_id'], ),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['mentor'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['mentor_type'], ['profession_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_professionals_username'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_name'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_linkedIn'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_email'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_organisations_website'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_email'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_table('opportunities')
    op.drop_table('student_level')
    op.drop_table('profession_type')
    op.drop_table('locations')
    op.drop_table('Interests')
    # ### end Alembic commands ###
